spring:
  datasource:
    url: jdbc:postgresql://demo-dev-3448.7s5.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb
    username: ajith
    password: JxuXnZEQU95HpYVSfGPphg
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
